#include "node.h"

using namespace avs8086::ast;

/* ========================================================================== */

const QHash<Node::Type, QString> Node::sm_typeNames = {
    { NODE_EOL,         "EOL" },

    // value
    { DUP,              "DUP" },
    { VALUE,            "Value" },
    { FLOAT,            "Float" },
    { OPERATOR,         "Operator" },
    { IDENTIFIER,       "Identifier" },

    { PROGRAM,          "Program" },
    { DEFINE,           "Define" },
    { WELL,             "'#'Instruction" },

    // expression
    { COMMA,            "Comma" },
    { COMMA_ARRAY,      "Comma Array" },

    { REGISTER,         "Register" },
    { REG_UNION,        "Register Union" },
    { ADDRESS,          "Address" },

    { MAKE_X,           "MAKE_X" },
    { ASSIGN,           "Assign" },

    { EXPR_STMT,        "Expression Statement" },

    { MOV,              "MOV" },
    { PUSH,             "PUSH" },
    { POP,              "POP" },
    { XCHG,             "XCHG" },
    { SINGLE,           "Single Instruction" },

    { NOT,              "NOT" },
    { AND,              "AND" },
    { OR,               "OR" },
    { XOR,              "XOR" },
    { TEST,             "TEST" },
    { SAL,              "SAL" },
    { SAR,              "SAR" },
    { SHL,              "SHL" },
    { SHR,              "SHR" },
    { ROL,              "ROL" },
    { ROR,              "ROR" },
    { RCL,              "RCL" },
    { RCR,              "RCR" },

    { XLAT,             "XLAT" },
    { LAHF,             "LAHF" },
    { SAHF,             "SAHF" },
    { PUSHF,            "PUSHF" },
    { POPF,             "POPF" },
    { CBW,              "CBW" },
    { CWD,              "CWD" },
    { AAA,              "AAA" },
    { DAA,              "DAA" },
    { AAS,              "AAS" },
    { DAS,              "DAS" },
    { INTO,             "INTO" },
    { IRET,             "IRET" },
    { REP,              "REP" },
    { REPE,             "REPE" },
    { REPZ,             "REPZ" },
    { REPNE,            "REPNE" },
    { REPNZ,            "REPNZ" },
    { MOVSB,            "MOVSB" },
    { MOVSW,            "MOVSW" },
    { CMPSB,            "CMPSB" },
    { CMPSW,            "CMPSW" },
    { SCASB,            "SCASB" },
    { SCASW,            "SCASW" },
    { LODSB,            "LODSB" },
    { LODSW,            "LODSW" },
    { STOSB,            "STOSB" },
    { STOSW,            "STOSW" },
    { CLC,              "CLC" },
    { STC,              "STC" },
    { CMC,              "CMC" },
    { CLD,              "CLD" },
    { STD,              "STD" },
    { CLI,              "CLI" },
    { STI,              "STI" },
    { WAIT,             "WAIT" },
    { LOCK,             "LOCK" },
    { HLT,              "HLT" },
    { NOP,              "NOP" },
    { AAM,              "AAM" },
    { AAD,              "AAD" },

    { JMP,              "JMP" },
    { JO,               "JO" },
    { JNO,              "JNO" },
    { JB,               "JB" },
    { JC,               "JC" },
    { JNAE,             "JNAE" },
    { JAE,              "JAE" },
    { JNB,              "JNB" },
    { JNC,              "JNC" },
    { JE,               "JE" },
    { JZ,               "JZ" },
    { JNE,              "JNE" },
    { JNZ,              "JNZ" },
    { JBE,              "JBE" },
    { JNA,              "JNA" },
    { JA,               "JA" },
    { JNBE,             "JNBE" },
    { JS,               "JS" },
    { JNS,              "JNS" },
    { JP,               "JP" },
    { JPE,              "JPE" },
    { JNP,              "JNP" },
    { JPO,              "JPO" },
    { JL,               "JL" },
    { JNGE,             "JNGE" },
    { JGE,              "JGE" },
    { JNL,              "JNL" },
    { JLE,              "JLE" },
    { JNG,              "JNG" },
    { JG,               "JG" },
    { JNLE,             "JNLE" },
    { JCXZ,             "JCXZ" },
};

/* ========================================================================== */
